### ISSUE TITLE
Pazar günü video

### ISSUE THREAD

**Issue by KeremAdiguzel** [temelt/DernekYS#1]
Bu pazar gününün videosu varsa bana gönderebilirmisiniz Teşekkürler.
m.keremadiguzel@yahoo.com.tr

**Comment by Guldenakin** [comment]
Tabiki gönderirim.Nasıl göndericem ? 

Date: Sun, 13 Mar 2016 05:56:12 -0700

**Comment by KeremAdiguzel** [comment]
Mail için boyut fazla gelir galiba ama dropbox google drive vs. uygunsa size

**Comment by Guldenakin** [comment]
https://drive.google.com/open?id=0B-AHqSgw8GPjVmFJV1lIQlZHUVU
drive a attım. Alabilirsin.

Date: Sun, 13 Mar 2016 06:18:51 -0700

**Comment by Guldenakin** [comment]
Aldınız mı ?

Date: Sun, 13 Mar 2016 06:18:51 -0700

**Comment by patateskafa** [comment]
acaba cumartesi gününün videoları olan var mı?

**Comment by KeremAdiguzel** [comment]
Drivedan almak için bastım ama erişim izni istiyorum Mail. gelmiştir 


https://www.dropbox.com/sh/m5f9ke9c8ake7ll/AABuB-zmP9H_DTUwtpsJNd9fa?dl=0 cumartesi videoları son yüklediklerim jsf 'ler

**Comment by KeremAdiguzel** [comment]
aldım şimdi çok teşekkürler.
